### ISSUE TITLE
TopArkServers --> TopGameServers and Voting API

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#314]
TopArkServers recently put out an announcement of migrating their site to their parent domain, TopGameServers. Servers that have premium featuring can file a ticket to migrate early and still keep the bulk of their data. However, it is more than likely that the functionality for voting API will be suspended. This will be problematic for servers that utilize the TopArkServers voting keys to generate server interest and voting rewards. 

<img width="838" alt="f95ab51a9fbaccfdb6a28990feb6b48e" src="https://user-images.githubusercontent.com/44717221/209243470-ecf6b5c6-9d88-437e-810c-42c654bd4c8b.png">

![image](https://user-images.githubusercontent.com/44717221/209243491-a3dd94e9-cc19-432c-b127-4f50c5ce4d1c.png)

**Comment by mvaessen** [comment]
Thanks for posting!

I think pretty much any other time of the year would be more convenient to announce and roll out an update like this, by the owners of that website. But I guess not everyone is busy right now preparing for Christmas and NYE.

I will look into this in January. For the time being (and perhaps beyond) I recommend using other vote sites.

Merry Christmas @Decollates !

**Comment by mvaessen** [comment]
This should be resolved now

**Comment by Decollates** [comment]
Still having an issue with GSA's system acknowledging voting rewards through TopGameServers. Their API seems to indicate that a reward has been dispersed, but I don't receive anything in the voting log acknowledging my account's vote, nor does using the discord bot's !claim feature activate my voting reward trigger. 
![image](https://user-images.githubusercontent.com/44717221/213896232-c7fccaae-cddc-42c5-b075-d8ba9c215e58.png)
![image](https://user-images.githubusercontent.com/44717221/213896238-91eb8bb8-e515-41e3-bf29-52d1b61ad658.png)
![image](https://user-images.githubusercontent.com/44717221/213896246-a1032e38-3174-4025-bedd-b29af9d28b54.png)
![image](https://user-images.githubusercontent.com/44717221/213896257-81e3e386-8874-4bfa-985d-04e8a87ae524.png)

**Comment by Decollates** [comment]
Also  got a new API voting key re-assigned to that particular server, and still the GSA log doesn't indicate any activity in the voting log.

**Comment by mvaessen** [comment]
Hi,

I've added some debugging info to help understand why it's not working. Would you mind trying voting on 1 server and claiming it for me please?

**Comment by Decollates** [comment]
I just went and voted for my Fjordur server (TopGameServers will only let the 'display' server of a cluster be voted for) and attempted to !claim it in my discord - nada.

**Comment by Decollates** [comment]
I'm very sorry, but I'm having trouble locating the "claim" button on the community website....

**Comment by Decollates** [comment]
Found it -- I attempted to claim through the website.

**Comment by mvaessen** [comment]
Thanks! Still not seeing any debug data, so I'm going to dig a little deeper to see what is going on

**Comment by mvaessen** [comment]
Hi, I looked into the problem further and noticed that the response was changed as well.

The API docs didn't really help me understand what I had to change, and while trying to join their Discord to ask for some guidance I noticed this: 
![Screenshot 2023-01-25 at 12 27 25](https://user-images.githubusercontent.com/13402423/214552239-9b273ad2-4e95-436f-a333-39f4934f1f1d.png)

Not sure why that happened. But I kinda feel like I'm wasting my time on a vote site few customers use.
Maybe you can contact them and ask for some guidance.

**Comment by Decollates** [comment]
Well then. That is extremely disappointing, but I hope it’s a fluke. I’ve spent quite a lot of money for their premium server advertisement and mean to make as much use out of their voting system as I can, without abandoning the GSA system or being forced to use their voting plugin. I will reach out and report what I find.

**Comment by Decollates** [comment]
I checked with TopGameServers, they say that they don't have any bans with your name associated. 
![image](https://user-images.githubusercontent.com/44717221/214656755-b5b32d12-f87a-4e01-af68-ad6646431903.png)

You might need to create an account with TopGameServers and link your discord. There's a discord verification system that auto-kicks users that have not verified their account. 
https://discord.gg/topgameservers
https://topgameservers.net/

**Comment by mvaessen** [comment]
I'll try looking into it this week. Maybe you can suggest they reconsider the number of hoops they force people to jump through. Some might end up deciding to drop support eventually.

**Comment by Decollates** [comment]
Thanks for not giving up on this, Max. I really hope we can keep using TopGameServers as a voting avenue, given that they appear to have a huge pull of traffic for server advertisement and engagement with players.

**Comment by mvaessen** [comment]
Hi, can you try claiming one more time for me please? The problems is still active, just hoping to gather some information.

**Comment by Decollates** [comment]
> Hi, can you try claiming one more time for me please? The problems is still active, just hoping to gather some information.

Just gave it another shot. I hope it works!

**Comment by mvaessen** [comment]
Awesome, i got some info. Can you try again for the same server so i can see what happens when you try to claim when it's already claimed?

**Comment by Decollates** [comment]
Done!

**Comment by mvaessen** [comment]
thanks! it does not appear to return a different value. To be sure, was there a vote to claim the first time you tried?

Response first attempt:
`{"voterewards_premium":false,"user_banned":false,"user_name":"decollates","status":"claimed","recently_claimed":true,"unclaimed_votes":0,"next_vote":"2023-01-25 08:47:33","error_reason":""}`

Response second attempt:
`{"voterewards_premium":false,"user_banned":false,"user_name":"decollates","status":"claimed","recently_claimed":true,"unclaimed_votes":0,"next_vote":"2023-01-25 08:47:33","error_reason":""}`

**Comment by Decollates** [comment]
There should have been, yes. I just made a secondary vote and attempted to claim it just now.

**Comment by mvaessen** [comment]
alright, this time it does look different, so that appears to work:
`{"voterewards_premium":false,"user_banned":false,"user_name":"decollates","status":"unclaimed","recently_claimed":false,"unclaimed_votes":4,"next_vote":"2023-01-26 18:18:11","error_reason":""}`

I pushed an update for the changed response, so new claims should be picked up now. Could you please try for 1 other server?

**Comment by Decollates** [comment]
I did cast a vote for another server and used the claim command in discord, and it looks like it activated the trigger task that disperses my voting rewards*. I did make sure to update the voting key - and it looks like the GSA dashboard voting log picked it up. 

*For some reason the task failed even though it’s supposed to ignore player/game server status and targeted my character that happened to be on an offline test server.

**Comment by mvaessen** [comment]
Sounds like it's working now. You can check the vote log to confirm. But since the task got triggered it means it did register. Thanks for the update!

**Comment by Decollates** [comment]
Revisiting this - with TopGameServers, the GSA voting system is recognizing the voting API in the logs, but it isn't activating tasks or triggers when the !claim command is made in discord or through the website.

**Comment by mvaessen** [comment]
Hi, based on the task log it did trigger. Probably related to settings.

![Screenshot 2023-02-03 at 07 52 19](https://user-images.githubusercontent.com/13402423/216532137-63f7e2be-c078-4b1e-ad34-2e45efcedb42.png)
![Screenshot 2023-02-03 at 07 52 26](https://user-images.githubusercontent.com/13402423/216532144-041d1ca4-2ce1-4b2e-a68a-c0b9ab36a945.png)

**Comment by Decollates** [comment]
The one for Crystal Isles was me voting for the CI server on ark-servers.net, a different voting website. I voted for Fjordur on TGS and the task for it wouldn’t trigger.

**Comment by mvaessen** [comment]
Hi, are you sure there is no issue on your end? 

If the vote is picked up by the vote log, then all the actions from there (triggering tasks etc) all use the same code. So if it works for 1 site, it will work for all other vote sites. Can you please make sure your task settings aren't causing the problem.

Maybe you can try and setup a simple task that triggers for all votes, to make it easy to spot and rule out any issues.

**Comment by Decollates** [comment]
Following through with this.

For some reason, when I had individual voting trigger tasks set up for each individual server, TopGameServers wouldn't register. Now that I have one active task set to activate for all servers, it works.
