### ISSUE TITLE
[ARK] GiveXP issue 

### ISSUE THREAD

**Issue by arkfrance** [gameserverapp/Platform#48]
__Please make sure to leave out any sensitive information__!

**Describe the bug**

The give xp integration mod is not working

**To Reproduce**
1. Got to the shop
2. Buy the give xp package
3. Nothing happen next
4. got a fail request

**Screenshots**

https://prnt.sc/QMOKIUts1r6p
https://prnt.sc/I5xiW3uGttkw

**Comment by mvaessen** [comment]
Thanks for the report!

There was an issue with the field that resulted in the value being stored under the wrong name. I'm hoping to include this in todays release. 

You will need to update the places where you used the Give EXP action, to solve the form issue.

**Comment by mvaessen** [comment]
@arkfrance the issue should be fixed now. Can you test it for me please?
Make sure to re-save the old EXP value on the shop pack.

**Comment by arkfrance** [comment]
working in game but i still get the request fail here : https://prnt.sc/UUD-4q8F1ycs

**Comment by mvaessen** [comment]
hm, thats odd. I created a similar action that shows the following response for me
![Screenshot 2022-02-21 at 17 53 40](https://user-images.githubusercontent.com/13402423/154998113-55de5e27-e5bc-41a1-b6cd-0069882a8e28.png)

Since it worked in-game for you I'm gonna assume this is just ARK acting weird on the response message. If you experience issues with it please re-open this issue!
