### ISSUE TITLE
ARK SE: Mod not working properly

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#791]
**Describe the bug**
Follow up from: https://discord.com/channels/315049169071112193/1214856193412042773

6/03/2024, 11:22 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:23 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:23 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:24 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:24 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:25 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec
06/03/2024, 11:25 [GSA] [ButtonModal] No Valid Response Retrieved, Retrying in 30sec

from 25282 / bsxucpkte as example. Running on every server that's running ARK SE

**Comment by Krajcara** [comment]
every time I start ARK server I get following error
[2024.03.08-02.38.40:971][ 87]2024.03.08_02.38.40: [GSA] Testmod not present

Any solution for this?

**Comment by LimitlessDrag0n** [comment]
This message is not an error. That's "normal" and can be ignored.

**Comment by Krajcara** [comment]
ok then, but why then i cant use the shop?

**Comment by mvaessen** [comment]
> ok then, but why then i cant use the shop?

Hi, please keep the issue on topic. I already explained on discord what the error message was (it checks whether the test mod is active).

**Comment by mvaessen** [comment]
Just tested and I can't reproduce the issues. Since we had similar issues reported for ASA (which disappeared as quickly as it came up) i'm going to assume that this one is also fixed now

**Comment by LimitlessDrag0n** [comment]
What more info do you need or can I provide? All my ARK SE servers still showing up the message above.

When pressing F2 
![image](https://github.com/gameserverapp/Platform/assets/99832504/4e4c1080-2465-4a15-ab34-3e06a1aff757)

Discord message only works half, Message from ingame to discord not working/Sometimes because other chats goes through

![image](https://github.com/gameserverapp/Platform/assets/99832504/ddd4d4e5-c28d-4b3a-88d8-337427fb4b52)

And yeah, every message from above on all SE servers I have

**Comment by mvaessen** [comment]
since you mentioned there are issues with chat being picked up, i recommend checking whether the chat log is showing on the dashboard at all. I also recommend checking the activity pages for the server that is having trouble. 

useful info that should help me better understand:
- game server logs
- activity page history
- chat log page, showing chat is / is not being picked up


the more details, the quicker I should be able to narrow down the potential cause

**Comment by LimitlessDrag0n** [comment]
There is one thing why maybe some chats are not going through. 
![image](https://github.com/gameserverapp/Platform/assets/99832504/af0827a5-2431-476f-8116-35f3251fb3d8)

Nothing else is showing up for the issue that the shop is not opening. 

![image](https://github.com/gameserverapp/Platform/assets/99832504/94b0bec7-9469-4f2d-94d0-0099d43d2483)

![image](https://github.com/gameserverapp/Platform/assets/99832504/b7dceb2e-5b6f-4c45-8b8c-5b2ff8083b60)

![image](https://github.com/gameserverapp/Platform/assets/99832504/426836e6-1196-4e49-ac90-b4a84f4fa649)

![image](https://github.com/gameserverapp/Platform/assets/99832504/40b82bcb-9fa5-471f-8917-9d743ffa3387)


I really dont see anything about the mod throwing errors except the character file thing but I think that's unreleated to the message I get.

**Comment by mvaessen** [comment]
based on the errors from the logs i would think there is an issue with the api keys.

Can you try again on a clean server with default config (no changes) and the GSA mod installed?

**Comment by LimitlessDrag0n** [comment]
![image](https://github.com/gameserverapp/Platform/assets/99832504/d90f5c06-a4a3-4ed9-9441-f2b8a3d52c5a)

![image](https://github.com/gameserverapp/Platform/assets/99832504/bb474ed2-388e-46ba-8087-9d3ba20da77c)

Same thing

**Comment by mvaessen** [comment]
alright, thanks for confirming.

I'll run some tests later to see whether i can reproduce. To be sure, is this a linux or windows machine? And which version

**Comment by LimitlessDrag0n** [comment]
Those are running on Linux, Debian 12.

**Comment by mvaessen** [comment]
Looks like the issue is caused by HTTPS not working properly in ASE.

Try adding the code below to your `/ShooterGame/Saved/Config/LinuxServer/Engine.ini`:
```
[/Script/Engine.NetworkSettings]
n.VerifyPeer=false
```

GSA will automatically set this up later, but for now this will let you fix the problem.

**Comment by LimitlessDrag0n** [comment]
Thanks, will check if I can add it. My linux skills to find and open the container are not that good :D
