### ISSUE TITLE
Unable to 'destroy' Old/Archived Dedi-connect game server from disconnected Dedi-connect machine

### ISSUE THREAD

**Issue by Eurymachus** [gameserverapp/Platform#847]
**Describe the bug**
As stated when attempting to 'destroy' old dedi-connect game servers there is just the spinning loading wheel of death.

**To Reproduce**
1. Go to 'Game Servers' and 'DANGER ZONE'
2. Click on 'Destroy'

**Expected behavior**
Confirmation dialogue should appear confirming destruction of chosen archived server

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/1562316/4c164c8e-1164-4429-bc6a-68010f75f04e)

**Comment by mvaessen** [comment]
hi, could you please post the game server id, so i can look up the game server?

**Comment by mvaessen** [comment]
Nevermind, was able to reproduce. This should now be fixed. Please give it a try

**Comment by Eurymachus** [comment]
My apologies I didn't get this notification. I was just trying some clean up. The original issue seems to be resolved, but now when I click on the destroy button I get this issue:
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/a7a61255-c1c6-4075-b9b6-134b0f5bc34a">

Cheers dude! <3

**Comment by Eurymachus** [comment]
Looks like the bot has moved this to the wrong place? It's still not working :D

**Comment by mvaessen** [comment]
hi, this should be fixed now. Please give it a try and let me know if it worked or not :)

**Comment by Eurymachus** [comment]
Amazing, it's working! Thank you <3
